# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: 'Ubuntu-16.04'

variables:
  imageName: 'pipelines-javascript-docker'

steps:
- task: Docker@2
  inputs:
    containerRegistry: 'docker repo 1'
    command: 'login'
- task: Docker@2
  displayName: Build and push an image
  inputs:
    command: buildAndPush
    Dockerfile: app/Dockerfile
    containerRegistry: 'docker repo 1'
    repository: 'azpipeline1'
    tags: 'v1'


